### ISSUE TITLE
License file in pypi archive

### ISSUE THREAD

**Issue by toddrme2178** [Calysto/calysto#10]
The pypi source archive isn't including the `LICENSE` file. Would it be possible to add it? It is very helpful when packaging this for Linux distributions. Thank you.

**Comment by dsblank** [comment]
The LICENSE file should now be included in the pypi calysto 1.0.6 downloads. Thanks! Let us know if this doesn't work.

**Comment by toddrme2178** [comment]
Thank you!
>
>
