### ISSUE TITLE
Issues on Ubuntu 14.04/Anaconda

### ISSUE THREAD

**Issue by tildebyte** [Calysto/calysto#4]
I don't know if you'd like me to open a separate issue for each bullet point...
 - OOB, requires `libXrender` and `libfontconfig` (documentation issue).
 - `pip install --update skulpt-kernel` doesn't work:
  - `"no such option: --update"`
 - `pip install --upgrade skulpt-kernel` doesn't work:
  - `"Could not find any downloads that satisfy the requirement skulpt-kernel
  No distributions at all found for skulpt-kernel"`
 - Downloading the github tarball and manually running `python ./setup.py install` completes without error, starting ipython NB server works, starting a new Skulpt notebook works, and executing Python code "works", **but**...
 - Nothing happens, other than the `Canvas #foo:` output

EDIT: derp
As stated, Ubuntu Server 14.04 running on EC2
Continuum's Anaconda-2.1.0-Linux-x86_64
iPython 3.0
Latest meta-kernel & calysto installed via `pip`

**Comment by tildebyte** [comment]
OTOH, I feel compelled to say - Holy smokes. Amazing work. I've been contributing to the Processing.py project (mostly porting over existing Java Processing examples), and this is veeery nice. I'm not a huge fan of the Processing IDE...

**Comment by dsblank** [comment]
Thanks for the issues, and feedback!

The `--update` command should have been `--upgrade`... that has been corrected on the different README.md pages now.

The skulpt-kernel is still underdevelopment; we'll get that in pypi as soon as it is a bit more stable. But you should be able to see something if you install from git. Do you have errors in your JavaScript console?

**Comment by tildebyte** [comment]
Ah. Mixed content error, probably.

````js
13:28:17.656 Using //@ to indicate sourceMappingURL pragmas is deprecated. Use //# instead jquery.min.js:1:0
13:28:17.954 Use of getPreventDefault() is deprecated.  Use defaultPrevented instead. jquery.min.js:5:0
13:28:18.099 Use of Mutation Events is deprecated. Use MutationObserver instead. jquery.min.js:5:0
13:28:18.389 Blocked loading mixed active content "http://cs.brynmawr.edu/~dblank/skulpt/skulpt.min.js?v=20150318171527"[Learn More] require.js:1903:0
13:28:18.390 Blocked loading mixed active content "http://cs.brynmawr.edu/~dblank/processing/processing.js?v=20150318171527"[Learn More] require.js:1903:0
13:28:18.445 Error: Script error for: http://cs.brynmawr.edu/~dblank/skulpt/skulpt.min.js
http://requirejs.org/docs/errors.html#scripterror require.js:166:16
13:28:18.445 Error: Script error for: http://cs.brynmawr.edu/~dblank/processing/processing.js
http://requirejs.org/docs/errors.html#scripterror

````

**Comment by tildebyte** [comment]
Yup. Enabling mixed content makes it all go away ;)

**Comment by dsblank** [comment]
How do you enable mixed content?

**Comment by tildebyte** [comment]
In Firefox: click on the shield icon to the left of the address bar. You should see "Insecure Content" with a dropdown next to it. The dropdown has one item: "Disable protection".
i.e. this is a browser-side "fix", not server-side.

**Comment by dsblank** [comment]
Ok, thanks.

What were you attempting to do that needed libXrender and libfontconfig? What was the error?

**Comment by tildebyte** [comment]
It was from `ipython` when first opening a skulpt notebook:
`/home/ubuntu/anaconda/bin/python: libfontconfig.so.1: cannot open shared object file: No such file or directory`
and then
`/home/ubuntu/anaconda/bin/python: libXrender.so.1: cannot open shared object file: No such file or directory`

**Comment by tildebyte** [comment]
So, from what I gather, if the js blobs (skulpt.min.js, processing.js etc.) are made available via https, the mixed content issue should go away.

**Comment by dsblank** [comment]
Thanks for the hint on the https. I'll try to find someplace to host those supporting https.

**Comment by dsblank** [comment]
Github supports serving javascript via https. I have updated kernels for Skulpt Python and MetaKernel Processing. Both languages now should work without having to allow mixed content.

I think all of your issues here have been addressed. Thanks again!
